"""empty message

Revision ID: 18258b7af005
Revises: 37077ac2af4d
Create Date: 2020-02-07 00:57:37.342266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18258b7af005'
down_revision = '37077ac2af4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
