"""empty message

Revision ID: 37077ac2af4d
Revises: d903918c37c0
Create Date: 2020-02-07 00:47:44.564342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37077ac2af4d'
down_revision = 'd903918c37c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('genre')
    op.add_column('Artist', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Artist', 'Genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'genre_id')
    op.create_table('genre',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='genre_pkey')
    )
    op.drop_table('Genre')
    # ### end Alembic commands ###
