"""empty message

Revision ID: 5d646cc94a6e
Revises: 0f15e15f808a
Create Date: 2020-02-07 01:49:31.381350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d646cc94a6e'
down_revision = '0f15e15f808a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=False))
    op.drop_column('Artist', 'genre_id')
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.add_column('Artist', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
