"""empty message

Revision ID: 88f4bb4dbb9b
Revises: acb39f06f064
Create Date: 2020-02-07 01:37:05.307139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88f4bb4dbb9b'
down_revision = 'acb39f06f064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('Venue', sa.Column('genre_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Genre', ['genre_id'], ['id'])
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'genre_id')
    op.alter_column('Artist', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
