"""empty message

Revision ID: dbfc1458e01f
Revises: 88f4bb4dbb9b
Create Date: 2020-02-07 01:39:14.460669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbfc1458e01f'
down_revision = '88f4bb4dbb9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genre_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'Genre', ['genre_id'], ['id'])
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'genre_id')
    # ### end Alembic commands ###
